# -*- coding: utf-8 -*-
"""basicstatistics1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gVdTz7QGU-gmFvK9HVJrPB-CLsb7OoZM
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

basic = pd.read_csv('/content/sales_data_with_discounts.csv')
basic

basic.info()

basic.columns

basic.describe()

basic.hist(figsize=(15,7))
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 10))

for i, col in enumerate(numerical_columns, 1):
    plt.subplot(3, 2, i)
    sns.boxplot(data=df[col], color='lightgreen')
    plt.title(f'Boxplot of {col}')

plt.tight_layout()
plt.show()

categorical_columns = ['Day', 'City', 'BU', 'Brand']

plt.figure(figsize=(10, 10))

for i, col in enumerate(categorical_columns, 1):
    plt.subplot(2, 2, i)
    sns.countplot(data=df, x=col, palette='Set2')
    plt.title(f'Frequency of {col}')
    plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

from sklearn.preprocessing import StandardScaler

# Create a copy to preserve the original data
df_standardized = df.copy()

# Initialize the scaler
scaler = StandardScaler()

# Standardize the numerical columns
df_standardized[numerical_columns] = scaler.fit_transform(df[numerical_columns])

# Show before and after comparison
print("Before Standardization (first 5 rows):")
print(df[numerical_columns].head())

print("\nAfter Standardization (first 5 rows):")
print(df_standardized[numerical_columns].head())

#One-hot encode categorical columns
df_encoded = pd.get_dummies(df, columns=categorical_columns)

# Display a portion of the transformed dataset
df_encoded.head()